[project]
name = "kooplexquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.1"
dependencies = [
    "pandas>=2.3.3",
    "sqlalchemy>=2.0.44",
]
